### ISSUE TITLE
Infer initial state

### ISSUE THREAD

**Issue by fraterenz** [fraterenz/ecdna-evo#33]
Instead of assuming that the ecDNA appears in one cell with one copy for the first time, infer the initial state i.e. the number ecDNA copies found in the first founding cell.

## Todo

- [x] update README #32
- [x] remove `to_infer` from lib
- [x] change app: remove `to_infer`, add field `range_copies`, field `range_cells`
- [x] build app: fixed cells, range copies `{ "1": x1, } user input is 1, range_copies
- [x] add new field `initial_state` in `Run`
- [x] save abc: `ABCResult` has also initial mean and initial copy (only if only one cell present, else `NaN`) and the initial number of cells
- [x] plots init copies
